name: Add checklist comment to PR

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  verify:
    runs-on: ubuntu-latest
    permissions: write-all
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Retrieve version from VERSION
        run: |
          RELVER=$(cat VERSION | tr -d '[:space:]')
          echo "RELVER=$RELVER" >> $GITHUB_ENV
      
      - name: Retrieve app name from APPNAME
        run: |
          APPNAME=$(cat APPNAME)
          echo "APPNAME=$APPNAME" >> $GITHUB_ENV    
      
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          mode: upsert
          comment_tag: previewComment
          message: |
            # PR checklist
            
            Checklist:
            
            - [ ] Is this release [${{ env.RELVER }}] of ${{ env.APPNAME }}?
            - [ ] Have you reviewed the unbuilt diff generated by the workflow?
            - [ ] Have you updated `app/${{ env.APPNAME }}.qvf`?
            
            If you wish to merge:

            - Have this PR approved by a code owner
            - Merge this PR into main
            - Go to releases, an action will generate a draft release with docs + attached QVF
            - Make any updates, then submit the release

            Common issues:
            
            - Version number missing or incorrect (./VERSION file needs updating)
            - After merging, draft release doesn't update - this is usually because
              the action failed due to an old draft release with the same name.
              Delete the draft release, and re-run the action.
            - AppIds are referenced where images are used in sheets, etc. Ignore these
              changes as these are caused by the unbuild process.
